
export interface IPronosticoItem {
    avvenimentoKey: string,
    blackListMax: number,
    blackListMin: number,
    codiceAvvenimento: number,
    codiceClasseEsito: number,
    codiceClasseEsitoAAMS: number,
    codiceDisciplina: number,
    codiceEsito: number,
    codiceEsitoAAMS: number,
    codiceInfoAggiuntiva: number,
    codicePalinsesto: number,
    codiceScommessa: number,
    dataAvvenimento: number,
    descrizioneAvvenimento: string,
    descrizioneEsito: string,
    descrizioneManifestazione: string,
    descrizioneScommessa: string,
    fissa: boolean,
    formattedDataAvvenimento: string,
    formattedHandicap: string,
    handicap: number,
    handicapVariato: boolean,
    legameMassimo: number,
    legameMinimo: number,
    legameMultipla: number,
    live: boolean,
    liveDelay: number,
    multipla: number,
    pronosticoKey: string,
    providerId: number,
    quota: number,
    quotaVariata: boolean,
    risultato: string,
    scommessaKey: string,
    stato: number,
};
